import React, { useState, useEffect } from 'react';
import { User, LayoutPanelLeft, Copy, Check, ThumbsUp, ThumbsDown, RefreshCw, Volume2, Sparkles } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { oneDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
import './MessageBubble.css';

const MessageBubble = ({ message, onOpenArtifact, onRetry, onSpeak }) => {
  const isUser = message.sender === 'user';
  
  // Status rotation for "thinking"
  const statuses = [
    "Routing to optimal model...",
    "Analyzing context & vectors...",
    "Synthesizing response...",
    "Formulating insights..."
  ];
  const [statusIndex, setStatusIndex] = useState(0);
  const [copied, setCopied] = useState(false);
  const [codeCopiedIndex, setCodeCopiedIndex] = useState(null);

  const handleCopy = () => {
    if (message.text) {
      navigator.clipboard.writeText(message.text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleCopyCode = (codeString, index) => {
    navigator.clipboard.writeText(codeString);
    setCodeCopiedIndex(index);
    setTimeout(() => setCodeCopiedIndex(null), 2000);
  };

  useEffect(() => {
    if (message.isGenerating) {
      const interval = setInterval(() => {
        setStatusIndex((prev) => (prev + 1) % statuses.length);
      }, 1500);
      return () => clearInterval(interval);
    }
  }, [message.isGenerating]);

  return (
    <div className={`message-row ${isUser ? 'user-row' : 'ai-row'} animate-bounce-in`}>
      <div className="message-container">
        <div className="message-avatar">
          {isUser ? (
            <div className="user-avatar-circle">
              <User size={16} />
            </div>
          ) : (
            <div className="ai-avatar-circle">
              <img src="/logo.png" alt="AI" className="ai-avatar-img" />
            </div>
          )}
        </div>
        
        <div className="message-content">
          {message.isGenerating ? (
            <div className="thinking-skeleton">
              <div className="skeleton-pulse" />
              <span className="status-text">{statuses[statusIndex]}</span>
            </div>
          ) : (
            <>
              {/* Uploaded or Generated Image Preview */}
              {(message.hasImage || message.imageUrl || message.imageBase64) && (
                <div className="message-image-preview">
                  <img 
                    src={message.imageUrl || message.imageBase64} 
                    alt="Attached or Generated" 
                    loading="lazy"
                  />
                  {message.isGeneratedImage && (
                    <div className="image-gen-badge">
                      <Sparkles size={12} /> Generated by FLUX
                    </div>
                  )}
                </div>
              )}

              {/* Uploaded File (PDF / Doc) Badge */}
              {message.attachedFile && (
                <div className="attached-file-badge">
                  <span className="file-icon">📄</span>
                  <div className="file-details">
                    <span className="file-name">{message.attachedFile.name}</span>
                    <span className="file-meta">Ingested into RAG Document Ocean</span>
                  </div>
                </div>
              )}

              {/* Message Text with Markdown & Syntax Highlighting */}
              <div className="message-text markdown-content">
                {isUser ? (
                  <p>{message.text}</p>
                ) : (
                  <ReactMarkdown
                    remarkPlugins={[remarkGfm]}
                    components={{
                      code({ node, inline, className, children, ...props }) {
                        const match = /language-(\w+)/.exec(className || '');
                        const codeString = String(children).replace(/\n$/, '');
                        const blockIndex = node?.position?.start?.line || Math.random();

                        return !inline && match ? (
                          <div className="code-block-wrapper">
                            <div className="code-block-header">
                              <span>{match[1].toUpperCase()}</span>
                              <button 
                                onClick={() => handleCopyCode(codeString, blockIndex)}
                                className="copy-code-btn"
                              >
                                {codeCopiedIndex === blockIndex ? (
                                  <>
                                    <Check size={13} className="text-green-400" /> Copied!
                                  </>
                                ) : (
                                  <>
                                    <Copy size={13} /> Copy Code
                                  </>
                                )}
                              </button>
                            </div>
                            <SyntaxHighlighter
                              style={oneDark}
                              language={match[1]}
                              PreTag="div"
                              customStyle={{
                                margin: 0,
                                borderRadius: '0 0 8px 8px',
                                fontSize: '0.85rem',
                                padding: '14px',
                                background: '#0a0a0d',
                              }}
                              {...props}
                            >
                              {codeString}
                            </SyntaxHighlighter>
                          </div>
                        ) : (
                          <code className={className} {...props}>
                            {children}
                          </code>
                        );
                      }
                    }}
                  >
                    {message.text || ''}
                  </ReactMarkdown>
                )}
              </div>
              
              {/* Artifact Button */}
              {message.hasArtifact && (
                <div className="artifact-btn-wrapper">
                  <button className="btn-silver artifact-trigger" onClick={onOpenArtifact}>
                    <LayoutPanelLeft size={16} className="text-primary" /> 
                    <span>Open Generated Plan & Artifact</span>
                  </button>
                </div>
              )}
              
              {/* Footer Actions for AI Messages */}
              {!isUser && (
                <div className="message-actions-row">
                  <div className="action-icons">
                    <button className="icon-btn" title="Copy text" onClick={handleCopy}>
                      {copied ? <Check size={14} style={{ color: '#34d399' }} /> : <Copy size={14} />}
                    </button>
                    <button className="icon-btn" title="Read Aloud" onClick={() => onSpeak && onSpeak(message.text)}>
                      <Volume2 size={14} />
                    </button>
                    <button className="icon-btn" title="Good Response">
                      <ThumbsUp size={14} />
                    </button>
                    <button className="icon-btn" title="Bad Response">
                      <ThumbsDown size={14} />
                    </button>
                    <button className="icon-btn" title="Retry with another model" onClick={() => onRetry && onRetry(message.id)}>
                      <RefreshCw size={14} />
                    </button>
                  </div>
                  {message.modelInfo && (
                    <div className="message-footer-badge">
                      <span className="model-dot" />
                      <span>{message.modelInfo}</span>
                    </div>
                  )}
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default MessageBubble;
