import React, { useState, useEffect } from 'react';
import { Bot, User, LayoutPanelLeft, Copy, Check, ThumbsUp, ThumbsDown, RefreshCw, MoreHorizontal, Volume2 } from 'lucide-react';
import './MessageBubble.css';

const MessageBubble = ({ message, onOpenArtifact, onRetry, onSpeak }) => {
  const isUser = message.sender === 'user';
  
  // Status rotation for "thinking"
  const statuses = ["Routing to SambaNova...", "Extracting Vectors...", "Generating Artifact..."];
  const [statusIndex, setStatusIndex] = useState(0);
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (message.text) {
      navigator.clipboard.writeText(message.text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  useEffect(() => {
    if (message.isGenerating) {
      const interval = setInterval(() => {
        setStatusIndex((prev) => (prev + 1) % statuses.length);
      }, 1500);
      return () => clearInterval(interval);
    }
  }, [message.isGenerating]);

  return (
    <div className={`message-row ${isUser ? 'user-row' : 'ai-row'} animate-bounce-in`}>
      <div className="message-container">
        <div className="message-avatar">
          {isUser ? <User size={20} /> : <img src="/logo.jpeg" alt="AI" className="ai-avatar-img" />}
        </div>
        
        <div className="message-content">
          {message.isGenerating ? (
            <div className="thinking-skeleton">
              <div className="skeleton-pulse"></div>
              <span className="status-text">{statuses[statusIndex]}</span>
            </div>
          ) : (
            <>
              {message.hasImage && message.imageBase64 && (
                <div className="message-image-preview">
                  <img src={message.imageBase64} alt="Attached" />
                </div>
              )}
              <div className="message-text">
                {message.text}
              </div>
              
              {message.hasArtifact && (
                <button className="btn-silver artifact-trigger" onClick={onOpenArtifact}>
                  <LayoutPanelLeft size={16} /> Open Artifact
                </button>
              )}
              
              {!isUser && (
                <div className="message-actions-row">
                  <div className="action-icons">
                    <button className="icon-btn" title="Copy" onClick={handleCopy}>
                      {copied ? <Check size={15} className="text-green-500" /> : <Copy size={15} />}
                    </button>
                    <button className="icon-btn" title="Read Aloud" onClick={() => onSpeak && onSpeak(message.text)}>
                      <Volume2 size={15} />
                    </button>
                    <button className="icon-btn" title="Good Response"><ThumbsUp size={15} /></button>
                    <button className="icon-btn" title="Bad Response"><ThumbsDown size={15} /></button>
                    <button className="icon-btn" title="Retry with another model" onClick={() => onRetry && onRetry(message.id)}>
                      <RefreshCw size={15} />
                    </button>
                    <button className="icon-btn" title="More"><MoreHorizontal size={15} /></button>
                  </div>
                  {message.modelInfo && (
                    <div className="message-footer">
                      Generated by {message.modelInfo}
                    </div>
                  )}
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default MessageBubble;
