import React, { useState, useEffect } from 'react';
import { Bot, User, LayoutPanelLeft } from 'lucide-react';
import './MessageBubble.css';

const MessageBubble = ({ message, onOpenArtifact }) => {
  const isUser = message.sender === 'user';
  
  // Status rotation for "thinking"
  const statuses = ["Routing to SambaNova...", "Extracting Vectors...", "Generating Artifact..."];
  const [statusIndex, setStatusIndex] = useState(0);

  useEffect(() => {
    if (message.isGenerating) {
      const interval = setInterval(() => {
        setStatusIndex((prev) => (prev + 1) % statuses.length);
      }, 1500);
      return () => clearInterval(interval);
    }
  }, [message.isGenerating]);

  return (
    <div className={`message-row ${isUser ? 'user-row' : 'ai-row'} animate-bounce-in`}>
      <div className="message-container">
        <div className="message-avatar">
          {isUser ? <User size={20} /> : <img src="/logo.png" alt="AI" className="ai-avatar-img" />}
        </div>
        
        <div className="message-content">
          {message.isGenerating ? (
            <div className="thinking-skeleton">
              <div className="skeleton-pulse"></div>
              <span className="status-text">{statuses[statusIndex]}</span>
            </div>
          ) : (
            <>
              <div className="message-text">
                {message.text}
              </div>
              
              {message.hasArtifact && (
                <button className="btn-silver artifact-trigger" onClick={onOpenArtifact}>
                  <LayoutPanelLeft size={16} /> Open Artifact
                </button>
              )}
              
              {message.modelInfo && !isUser && (
                <div className="message-footer">
                  Generated by {message.modelInfo} in 1.2s
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default MessageBubble;
